@startuml ActitvityDiagramm
|Администратор|

|Организатор|
start
:Сформировать зал для мероприятия;
:Составить заявку на создание мероприятия;

|Администратор|
:Рассмотреть заявку на создание мероприятия;
if (Данные заполнены корректно?) then (да)

|Организатор|
:Мероприятие создано;
else (нет)
:Заявка удалена;
detach
endif
:Открыть продажу билетов;

|Покупатель|
:Найти мероприятие;
:Выбрать мероприятие;
:Зарезервировать место;
if (На счету достаточно средств?) then (да)
:Получить билеты по email;
else (нет)
:Оплата отменена;
:Место возвращено в продажу;
detach
endif

stop
@enduml