!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Context

Person(Visitor, "Посетитель [Пользователь]", "Поиск концертов, покупка билетов, отзывы")

Person(Administrator, "Администратор [Пользователь]", "Ищет концерты, покупает билеты, оставляет отзывы")

Person(Organizer, "Организатор [Пользователь]", "Размещение информации о концертах, управление продажами")

System(App, "Система Поиска и Резервирования Билетов на Концерты [Программная система]", "Платформа для поиска мероприятий, выбора мест, покупки и резервирования билетов на концерты, а также размещения и продвижения своих концертов")

System_Ext(FNS, "ФНС API [Программная система]", "Автоматизация извлечения данных из Единого государственного реестра юридических лиц (ЕГРЮЛ) и Единого государственного реестра индивидуальных предпринимателей (ЕГРИП)")

System_Ext(Email, "Cистема электронной почты [Программная система]", "Поставщик системы отправки электронной почты")

System_Ext(PaymentSystem, "Электронная платежная система [Программная система]", "Интернет-эквайринг, прием платежей")


Rel(Visitor, App, "Поиск концерта")
Rel(Administrator, App, "Модерация")
Rel(Organizer, App, "Размещение концерта")

Rel(App, FNS, "Проверка организатора")
Rel(App, Email, "Отправка писем")
Rel(App, PaymentSystem, "Оплата")