!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Continer

Person(Visitor, "Посетитель [Пользователь]", "Поиск концертов, покупка билетов, отзывы")

Person(Administrator, "Администратор [Пользователь]", "Ищет концерты, покупает билеты, оставляет отзывы")

Person(Organizer, "Организатор [Пользователь]", "Размещение информации о концертах, управление продажами")

System_Boundary(search_and_reservation_system, "Система Поиска и Резервирования Билетов на Концерты"){
    Container(mobile_app, "Мобильное приложение", "Flutter", "")

    Container(web_api, "Web API", "C#, .net", "Предоставляет функциональность системы через json/HTTPS API")

    ContainerDb(ReadDataBase, "База данных", "PostgreSQL", "")

    ContainerDb(SaveDataBase, "Объектное хранилище", "S3", "")

    SystemQueue(MessageBus, "Шина сообщений RabbitMQ", "Для обмена информацией между сервисами")
}

System_Ext(FNS, "ФНС API [Программная система]", "Автоматизация извлечения данных из Единого государственного реестра юридических лиц (ЕГРЮЛ) и Единого государственного реестра индивидуальных предпринимателей (ЕГРИП)")

System_Ext(Email, "Cистема электронной почты [Программная система]", "Поставщик системы отправки электронной почты")

System_Ext(PaymentSystem, "Электронная платежная система [Программная система]", "Интернет-эквайринг, прием платежей")

Rel(Visitor, mobile_app, "Поиск концерта")
Rel(Administrator, mobile_app, "Модерация")
Rel(Organizer, mobile_app, "Размещение концерта")

Rel(mobile_app, web_api, "[json, HTTPS] Запросы к API")
web_api --> ReadDataBase : "Запись/чтение данных"
web_api --> SaveDataBase : "Сохранение файлов"
web_api --> MessageBus : "Отправка и получение сообщений"

web_api --> FNS : "Проверка организатора"
web_api -> Email : "Отправка писем"
web_api --> PaymentSystem : "Оплата"
