@startuml
  !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

title Deployment Diagram

Deployment_Node(mob, "Мобильное устройство пользователя", "Deployment node: Apple IOS or Android"){
    Container(mobile, "Мобильное приложение", "Container: Flutter", "Предоставляет функционал поиска и резервирования билетов на концерты")
}

Deployment_Node(VK, "VK Cloud", "Deployment node: VK Cloud data center"){
    Deployment_Node(Ubuntu1, "", "Deployment node: Ubuntu 18.04"){
        Deployment_Node(WebServer, "", "Deployment node: web server kestrel"){
            Container(WebApi, "Web API", "Container: .Net", "Предоставляет функционал системы поиска и резервирования билетов через JSON/HTTPS API")
        }
    }

    Deployment_Node(Ubuntu2, "", "Deployment node: Ubuntu 18.04"){
        Deployment_Node(Postgres, "", "Deployment node: postgres 13"){
            ContainerDb(ReadDataBase, "База данных", "Container: PostgreSQL", "Хранение пользовательских данных и информации о концертах")
        }
    }

    Deployment_Node(Ubuntu3, "", "Deployment node: Ubuntu 18.04"){
        Deployment_Node(VKCloud, "", "Deployment node: VK Cloud Storage"){
            ContainerDb(SaveDataBase, "Объектное хранилище", "Container: S3", "")
        }
    }

    Deployment_Node(Ubuntu4, "", "Deployment node: Ubuntu 18.04"){
        Deployment_Node(RabbitMQ, "", "Deployment node: RabbitMQ 3.12"){
            SystemQueue(MessageBus, "Шина сообщений", "RabbitMQ", "")
        }
    }
}

mobile ..> WebApi : "Запросы к API [JSON/HTTPS]"

WebApi ..> ReadDataBase : "Запросы чтения и записи"

WebApi ..> SaveDataBase : "Сохранение файлов" 

WebApi ..> MessageBus : "Отправка сообщений в общую шину"

@enduml